pub use core;
pub use crc64fast;
pub use rand;
pub use zerocopy;
// pub use winapi;
// pub use winapi::shared::winerror::SUCCEEDED;
// pub use winapi::um::fileapi::{CreateFileA, OPEN_ALWAYS};
// pub use winapi::um::handleapi::INVALID_HANDLE_VALUE;
// pub use winapi::um::memoryapi::{MapViewOfFile, FILE_MAP_ALL_ACCESS};
// pub use winapi::um::winbase::CreateFileMappingA;
// pub use winapi::um::winnt::{PAGE_READWRITE, FILE_SHARE_WRITE, FILE_SHARE_READ, FILE_SHARE_DELETE, GENERIC_READ, GENERIC_WRITE, FILE_ATTRIBUTE_NORMAL, ULARGE_INTEGER};
