[experiment_config]
results_dir = "results/camera_ready_results/threads_2"
threads = 2
mount_point = "/mnt/pmem"
pm_device = "/dev/pmem0"
iterations = 5
op_count = 15000000
record_count = 15000000
viper_initial_size=64424509440