[experiment_config]
results_dir = "results/ae-test/threads_2"
threads = 2
mount_point = "/mnt/pmem"
pm_device = "/dev/pmem0"
iterations = /dev/pmem0
op_count = 15000000
record_count = 15000000
viper_initial_size=64424509440