[experiment_config]
results_dir = "results/20250401/threads_4"
threads = 4
mount_point = "/mnt/pmem"
pm_device = "/dev/pmem0"
iterations = 5
op_count = 1500000
record_count = 15000000
viper_initial_size=64424509440