[experiment_config]
results_dir = "results/artifact-evaluation/"
threads = 4
mount_point = "/mnt/pmem/"
pm_device = "/dev/pmem0"
iterations = 1
op_count = 1500000
record_count = 15000000
viper_initial_size=64424509440