[microbenchmark_config]
kv_file = "/mnt/pmem/capybarakv" 
pm_dev = "/dev/pmem0"
mount_point = "/mnt/pmem"
results_dir = "results/artifact_evaluation_results/threads_2"
experiment_keys = 25000000
per_record_list_len = 64
op_iterations = 1
start_iterations = 1

# capybarakv_region_size: 1024^3 * 115. this works well for 128GiB PM device
capybarakv_region_size = 123480309760 

viper_region_size = 53687091200

# each record has:
# - a 64B key with about 40B metadata (CRCs, record metadata)
# - a 1KiB item with 8B CRC
# - per_record_list_len 8-byte list elements, each of which 
#   has 24B metadata (next ptr and CRCs)
# max keys: 1024^3 * 115 / (64 + 40 + 1024 + 8 + 32*64)
max_keys = 38781504

run_full_setup = true
max_operations_per_transaction = 1
