[experiment_config]
results_dir = "results/mini_experiment_output/"
threads = 8
mount_point = "/mnt/pmem"
pm_device = "/dev/pmem0"
iterations = 1
op_count = 10000
record_count = 10000
viper_initial_size=1073741824