version: 1.4.{build}
os: Visual Studio 2017
platform: x64

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  GENERATOR: "Visual Studio 14 2015 Win64"

configuration:
- Debug
- Release

build_script:
- exit 0

test_script:
- exit 0
