name: artifact-ci
on: [push]
jobs:
  capybarakv-setup-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: setenv
        run: |
          echo "TERM=linux" >> $GITHUB_ENV
      - name: setup
        working-directory: osdi25/capybaraKV/evaluation
        run: JAVA_HOME=$JAVA_HOME_21_X64 ./setup.sh
      - name: verify
        working-directory: osdi25/capybaraKV/capybarakv/src
        run: ./verify.sh
  capybarans-setup-and-verify:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout 
        uses: actions/checkout@v4
      - name: setup
        run: |
          sudo apt update
          sudo apt install sloccount scons dotnet-sdk-8.0
          wget https://github.com/dafny-lang/dafny/releases/download/v4.10.0/dafny-4.10.0-x64-ubuntu-20.04.zip
          unzip dafny-4.10.0-x64-ubuntu-20.04.zip
      - name: build-and-verify
        working-directory: osdi25/capybaraNS
        run: |
          scons -c --dafny-path=../../dafny
          scons --dafny-path=../../dafny

          
